### ISSUE TITLE
Finish readthedocs setup

### ISSUE THREAD

**Issue by jhamman** [pangeo-data/intake-stac#10]
I haven't been able to get the readthedocs build to work for this package yet. Most builds just die without a proper error message (e.g. https://readthedocs.org/projects/intake-stac/builds/9123555/).

**Comment by martindurant** [comment]
Looks like maybe a temporary conda problem, dead repo server etc. Has this been the case for a while?

**Comment by TomAugspurger** [comment]
conda was serving bad repodata up until ~10 minutes ago.

**Comment by jhamman** [comment]
closed by #27
