### ISSUE TITLE
Allow opening of multiple assets

### ISSUE THREAD

**Issue by matthewhanson** [pangeo-data/intake-stac#12]
A single asset may have 1 band, or multiple bands. 

When opening up the assets as an xarray using intake, the user should be able to specify multiple assets and have them be appended to return a 3d xarray.

This will require some sort of validation checks, such as that the bands all share the same x and y size. This validation can be kept to a minimum for now.

**Comment by jhamman** [comment]
+1 on this. I think this is what I was trying to get at with #5. I think intake-xarray's [`RasterIOSource`](https://intake-xarray.readthedocs.io/en/latest/api.html#intake_xarray.raster.RasterIOSource] will allow us to pass it a list of urls and a concat dim.

**Comment by jhamman** [comment]
@jsignell and I sat down at scipy and discussed this issue a bit. What we came up with is something along the following idea:

- we probably don't want to automagically interpret bands as a single xarray array or dataset.
- we could easily add a method to `StacItem` that uses intake-xarray to stack bands at read time, this would return a Intake Entry that could be converted to xarray later. 

Here's an example of the possible `stack_bands` api:

```python
items = StacItem('/path/to/stac/items.json')  # e.g. https://landsat-stac.s3.amazonaws.com/landsat-8-l1/227/120/2017-11-23/LC82271202017327LGN00.json
list_of_bands = ['B1', 'B2']
new_entry = items.stack_bands(list_of_bands)
new_entry.to_dask()
```
