### ISSUE TITLE
Use markdown instead of rst for basic text files

### ISSUE THREAD

**Issue by matthewhanson** [pangeo-data/intake-stac#13]
Markdown is designed to be readable without being compiled, while RST is more focused on the compiled output. 

Top level text files, such as the changelog, README, contributing info, are often not going to be rendered and will be looked at as plain text and so should be in Markdown format.  

The documentation under docs should remain as rst since it is primarily used to render the documentation output.

**Comment by jhamman** [comment]
I'd be fine with either of these changes. We may decide to move the changelog and contributing info to the documentation, in which case, it may make more sense to keep them as RST. I don't have strong feeling here either way though.

**Comment by matthewhanson** [comment]
Makes sense, I moved contributing entirely to the docs, and then references that from the README.

The changelog I changed to .md as I think the vast majority of readers are going to look at this as a text file or rendered in GitHub.

Closing as resolved.
