### ISSUE TITLE
Move tests outside of package directory

### ISSUE THREAD

**Issue by matthewhanson** [pangeo-data/intake-stac#14]
Move intakestac/tests directory to top level 'test' to reflect the typical way of providing tests. This way they are not distributed along with the intake-stac package.

**Comment by jhamman** [comment]
I think the world is split on what is the right way to do this. Pytest says both are okay and I can find multiple packaging tutorials that indicate this is the way to go ([here's one](https://the-hitchhikers-guide-to-packaging.readthedocs.io/en/latest/creation.html#arranging-your-file-and-directory-structure)). My inclination is to leave this as is unless we have some inclination that the tests directory is to heavy for our distribution.

**Comment by matthewhanson** [comment]
OK with leaving it for now, but I would advocate for tests not being included in distributions as a general rule:

- There's no compelling enough use case for needing to run tests on installed packages that isn't easily worked around by just getting the complete install package. Any time that I wanted to run tests on a dependent library I would go to the source, not look in my installed versions.
- Maybe not for intake-stac right now, but tests can easily contain test files that add to the cruft, having tests in the package dir dissuades test writers from including valuable test data
- If everyone includes tests in their packages there could be a cumulative effect that is undesirable in the serverless world where deployment size is still a consideration. It should therefore be opposed on principal alone because it's good for the long term health of Python packages.

All that being said, I'm actually not even sure that a `tests` directory in a Python package would end up being included in the final distribution, because there might be some `setuptools` magic that excludes directories specified as test directories.  If there is, then this is all moot and including it in the package directory would be fine.
