### ISSUE TITLE
Add automatic publishing on new tag in CI/CD

### ISSUE THREAD

**Issue by matthewhanson** [pangeo-data/intake-stac#16]
Configure CircleCI to run tests (and required for PRs) and, upon pushing a new versioned tag, auto publish to PyPi.

See https://github.com/sat-utils/sat-stac/blob/master/.circleci/config.yml for an example.

**Comment by matthewhanson** [comment]
Didn't notice travis was already set up here, so this isn't needed, unless there's some reason to move away from travis. I generally prefer CircleCI, but if it works as is no reason to change it.

**Comment by matthewhanson** [comment]
Changed the title. Update the CI/CD pipeline to publish new versions to PyPi when a new versioned tag is released.

**Comment by jhamman** [comment]
Travis is (for me) usually the shortest path to CI. That said, I'm generally pleased with CircleCI and Azure Pipelines so if someone wanted to rework things here, that would be fine with me. 

As for automatic publishing of new tags, I'm a bit conflicted here. I'm just not sure we're going to issue enough releases to justify the effort. That said, I'm happy to give it a try if someone wants to try implementing it. I'd also advocate for documenting a minimum manual procedure for making releases, something like https://github.com/dask/dask/blob/master/docs/release-procedure.md.

**Comment by matthewhanson** [comment]
I've been trying to go more the route of "release early, release often" rather than my traditional way of trying to get everything done by the next release approach (which just keeps pushing the release).  The biggest driver here is that I think it's more important that potential users have the quickest easiest path to the latest version. If there is a long time between releases, and multiple changes, then more people will feel compelled to install from a branch, which is really not ideal.

Also I don't think this is a big lift to implement this, and it will pay off after a couple releases.  We can still use a Release Procedure so +1 on that. You will want to verify version and changelog updated, and a tag is pushed for instance.

**Comment by jhamman** [comment]
closed by #37
