### ISSUE TITLE
Consider changing approach to versioning

### ISSUE THREAD

**Issue by matthewhanson** [pangeo-data/intake-stac#17]
I find the versioning code to be a bit confusing, and might be a little overkill.   But maybe this is required due to being a plugin for intake?

If not, then I'd say we should just have a single version.py file to specify the version.

**Comment by jhamman** [comment]
We're vendoring [python-versioneer](https://github.com/warner/python-versioneer) which is pretty common practice. This is the same versioning approach that intake and intake-xarray are using so I'm inclined to stick with the current approach. There are a number of nice features with versioneer, but most importantly, it works as is. My inclination is to leave things as is - unless we start having problems.

**Comment by matthewhanson** [comment]
Ok, makes sense, it seemed rather convoluted to me, but if intake is using it then that's good enough for me, closing.
