### ISSUE TITLE
remove scikit-image dependency

### ISSUE THREAD

**Issue by scottyhq** [pangeo-data/intake-stac#30]
Scikit image is a 20Mb+ dependency. As far as I can tell it is required by intake-xarray (https://github.com/intake/intake-xarray/blob/c01f328d6157d1ba88c93ab6681834ea4c7c70b8/intake_xarray/image.py) so should instead be specified as a requirement of that intake extension and not here? 

I think we could also just remove it and use rasterio to open all images?

**Comment by jhamman** [comment]
My memory is that we end up using the skimage loader for thumbnails in various catalogs. I agree we shouldn't need to depend on it but I think we'll need to test things out before removing it outright.

**Comment by scottyhq** [comment]
should probably add this to documentation, but it's possible to pass any image reader that returns a numpy array for opening assets with the xarray_image driver 

https://github.com/intake/intake-stac/blob/c1a65ce1317d76929328fbdd554893cc10a4f6a4/intake_stac/catalog.py#L30-L32

(which passes through to intake.open_xarray_image, docstring here https://github.com/intake/intake-xarray/blob/bd43095c3f418aaf6f5cda0d3fbdf108243611e7/intake_xarray/image.py#L227)

So for example, this works:
```python
def myimread(image):
    import PIL.Image
    import numpy as np
    return np.array(PIL.Image.open(image))

da = asset(imread=myimread).to_dask()
da
```
