### ISSUE TITLE
Issue Reading Catalog from Private Bucket

### ISSUE THREAD

**Issue by nroberts-hub** [pangeo-data/intake-stac#33]
I am trying to access the catalog.json file via either https://dev-usgs-landsat.s3-us-west-2.amazonaws.com/collection01/level-1/standard/etm/2009/001/005/catalog.json or s3://dev-usgs-landsat/collection01/level-1/standard/etm/2009/001/005/catalog.json using Intake Stac and I am getting these errors.
For the Object URL:
![image](https://user-images.githubusercontent.com/51800243/70652515-563f4000-1c18-11ea-8ad2-e7f23b061599.png)

For the S3 Link:
![image](https://user-images.githubusercontent.com/51800243/70652723-bb933100-1c18-11ea-869a-60e6556adb68.png)

**Comment by TomAugspurger** [comment]
FYI, many people are at AGU this week so the response may be a bit delayed :)

Do you know who maintains the catalogs at that URL? Those error messages are consistent with the file not existing / not being publicly accessible.

**Comment by jhamman** [comment]
I get a PermissionDenied error when I hit that url. Is this a private object? If so, you’ll need to make sure your python process has the necessary environment credentials to allow access.

**Comment by pieschker** [comment]
What environment credentials outside of an IAM role granting access to the bucket?

**Comment by jhamman** [comment]
@pieschker, what happens when you hit the above urls with a simple python requests call, e.g. 

```python
In [7]: import requests

In [8]: url = 'https://raw.githubusercontent.com/sat-utils/sat-stac/master/test/
   ...: catalog/catalog.json'

In [9]: r = requests.get(
   ...:     url,
   ...:     headers={}
   ...: )
   ...: print(r.json())
{'id': 'stac', 'description': 'A STAC of public datasets', 'stac_version': '0.6.0', 'links': [{'rel': 'self', 'href': 'catalog.json'}, {'rel': 'root', 'href': 'catalog.json'}, {'rel': 'child', 'href': 'eo/catalog.json'}]}

In [10]: url = 'https://dev-usgs-landsat.s3-us-west-2.amazonaws.com/collection01
    ...: /level-1/standard/etm/2009/001/005/catalog.json'

In [11]: r = requests.get(
    ...:     url,
    ...:     headers={}
    ...: )
    ...: print(r.json())
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
<ipython-input-11-a7a0c1c7f3a3> in <module>
      3     headers={}
      4 )
----> 5 print(r.json())

~/miniconda3/lib/python3.6/site-packages/requests/models.py in json(self, **kwargs)
    887                 try:
    888                     return complexjson.loads(
--> 889                         self.content.decode(encoding), **kwargs
    890                     )
    891                 except UnicodeDecodeError:

~/miniconda3/lib/python3.6/json/__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    352             parse_int is None and parse_float is None and
    353             parse_constant is None and object_pairs_hook is None and not kw):
--> 354         return _default_decoder.decode(s)
    355     if cls is None:
    356         cls = JSONDecoder

~/miniconda3/lib/python3.6/json/decoder.py in decode(self, s, _w)
    337
    338         """
--> 339         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    340         end = _w(s, end).end()
    341         if end != len(s):

~/miniconda3/lib/python3.6/json/decoder.py in raw_decode(self, s, idx)
    355             obj, end = self.scan_once(s, idx)
    356         except StopIteration as err:
--> 357             raise JSONDecodeError("Expecting value", s, err.value) from None
    358         return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

This tells me that I don't have access to this url. If you are getting a similar error, I suggest examining your IAM roles.

**Comment by jhamman** [comment]
@nroberts-hub and @pieschker - can you suggest a path forward here? Were you able to resolve your access problems?

**Comment by pieschker** [comment]
Nope. It's a configuration issue with our environment that is beyond our control. We just have to wait for the data to be public. I suggest closing this issue. Thank you.
