### ISSUE TITLE
Move dask chunk specification to to_dask() method

### ISSUE THREAD

**Issue by scottyhq** [pangeo-data/intake-stac#35]
This came up in https://github.com/pangeo-data/intake-stac/pull/29#issuecomment-562462690

Currently in intake-stac (0.2.2) to set chunk size in intake, you (somewhat unintuitively ) invoke the entry:

```python
# syntax in intake-stac 0.2.2
da = entry.B1(chunks=dict(band=1,x=2048,y=2048)).to_dask()
```

Thoughts on re-factoring to a more intuitive syntax (maybe just incorporate into `read()` method to match the way intake works with csv files to return a pandas dataframe)?

```python
# returns xarray object with embedded dask arrays
da = entry.B1.read(chunks=dict(band=1,x=2048,y=2048)) 
```

**Comment by jhamman** [comment]
@scottyhq - this syntax comes from intake, not intake-stac. I'm sure @martindurant can provide the rational but either way, I don't think it would end in a change to intake-stac.

**Comment by scottyhq** [comment]
cross referencing related issue in intake-xarray https://github.com/intake/intake-xarray/issues/52

**Comment by jhamman** [comment]
I'm going to close this in favor of the above listed intake-xarray issue.
