### ISSUE TITLE
understanding the sat-stac --> intake object mapping

### ISSUE THREAD

**Issue by jhamman** [pangeo-data/intake-stac#4]
Intake-stac is simply an opinionated way to turn STAC into Intake. We're currently using sat-stac which has the following classes. 

- `Thing`: A Thing is not a STAC entity, it is a low-level parent class that is used by Catalog, Collection, and Item and includes the attributes they all have in common (read and save JSON, get links).
- `Catalog`: A catalog is the simplest STAC object, containing an id, a description, the STAC version, and a list of links.
- `Collection`: A Collection is a STAC catalog with some additional fields that describe a group of data, such as the provider, license, along with temporal and spatial extent.
- `Item`: The Item class implements the STAC Item, and has several convenience functions such as retrieving the collection, getting assets by common band name (if using the EO Extension)
- `Items`: The Items class does not correspond to a STAC object. It is a FeatureCollection of Items, possibly from multiple collections. It is used to save and load sets of Items as a FeatureCollection file, along with convenience functions for extracting info across the set.

Intake some natural analogs that we need to map these classes too:

- `Catalog`: Manages a hierarchy of data sources as a collective unit. A catalog is a set of available data sources for an individual entity (remote server, local file, or a local directory of files). This can be expanded to include a collection of subcatalogs, which are then managed as a single unit.
- `CatalogEntry`: A single item appearing in a catalog
- `DataSource`: An object which can produce data

I think it would be good to discuss, at a high-level, how to implement these mappings and to produce some documentation on the subject. 

cc @martindurant, @matthewhanson, @scottyhq, @jonahjoughin

**Comment by martindurant** [comment]
Certainly happy to take part here.

One thing that may be lacking on the Intake side, from the description above, is an explicit mechanism to build a source from a set of sources. A similar task is done in some places in Intake by scanning as set of files and using their metadata or path-names to place them in the final collection.

It *feels* to me like you might want to have a fully-nested hierarchical catalog exposing the lowest level item contents, with metadata pulled from the low level and the collection level too; then the cat object exposing them can have various collect/merge methods producing new combined datasets.

**Comment by jhamman** [comment]
In d16e6723a0788d7155d87cadc22eca12fe1c03bb, I've refactored the layout of the intake-stac Catalog to be roughly:

- `satstac.Catalog` --> `intake_stac.StacCatalog(intake.Catalog)`
- `satstat.Collection` --> `intake_stac.StacCollection(intake.Catalog)`
- `satstac.Item` --> `intake_stac.StacItem(intake.Catalog)`
- `satstac.Item.assets` --> `intake_stac.StacEntry(LocalCatalogEntry)`

Down the road, it would be a killer feature to have an `intake.StacFeatureCollection` class that can intelligently combine assets but that can wait.

I would love to get @matthewhanson's take on this mapping and what STAC concepts I may be missing.

**Comment by matthewhanson** [comment]
@jhamman This all seems reasonable to me, but I'm behind on my overall understanding of Intake. 
I'll spend some time on this early next week to get up to speed and might have something more intelligent to say then.

**Comment by jhamman** [comment]
Thanks @matthewhanson - I'd like to make this the central conversation topic for Tuesday's call so if you can take a look before then, that would be great.

**Comment by jhamman** [comment]
closed by #2
