### ISSUE TITLE
include in list of drivers?

### ISSUE THREAD

**Issue by martindurant** [pangeo-data/intake-stac#7]
Is this ready for inclusion at https://intake.readthedocs.io/en/latest/plugin-directory.html ?

**Comment by jhamman** [comment]
@martindurant - I'd be fine with this. Is some threshold of maturity you aim for in this list. I expect many things will change in intake-stac over the coming weeks but I don't mind advertising the project as a work in progress.

**Comment by martindurant** [comment]
As long as it's installable, some examples work and there is reasonable language around the status of the package in README/docs, that's good enough for me.
